public final class Mob {
	public long hash;
	public String name;
	public int index;
	public int field_497;
	public int cur_x;
	public int cur_y;
	public int field_500;
	public int field_501;
	public int field_502;
	public int field_503;
	public int field_504;
	public int field_505;
	public int[] waypoint_hist_x = new int[10];
	public int[] waypoint_hist_y = new int[10];
	public int[] sprites = new int[12];
	public String field_509;
	public int field_510;
	public int field_511;
	public int field_512;
	public int field_513;
	public int field_514;
	public int field_515;
	public int field_516;
	public int field_517 = -1;
	public int field_518;
	public int field_519;
	public int field_520;
	public int field_521;
	public int field_522;
	public int field_523;
	public int field_524;
	public int field_525;
	public boolean field_526 = false;
	public int field_527 = -1;
	public int field_528;
}
